Открывается и закрывается
htmlacademy-univer-javascript-1/2432009-kekstagram-4 pull request #9
Opened 2023-11-28 18:14 UTC by ElizavetaIlina

---
:mortar_board: [Открывается и закрывается](https://up.htmlacademy.ru/univer-js1/4/user/2432009/tasks/13)

2023-11-29 15:04 UTC, MaksimovG requested changes

2023-11-29 15:04 UTC, MaksimovG commented on js/view-popup.js
> +export const openViewPopup = (evt, url, description, likes, comments) =>{
зачем тут evt

2023-11-29 15:04 UTC, MaksimovG commented on js/view-popup.js
> +  }
переписать на foreach

2023-11-29 15:04 UTC, MaksimovG commented on js/view-popup.js
> +};
ошибки проверки.

2023-12-01 14:25 UTC, MaksimovG requested changes

2023-12-01 14:25 UTC, MaksimovG commented on js/view-popup.js
> +  evt.target.removeEventListener('click', closeViewPopup);
мы  находим элемент через document.querySelector. Один раз. и на один раз найденные элементы вешаем обработчик. я не лекции где-то вешал обработчик на evt target? а так же на лекции я показывал что целью клика может быть не совсем то, что мы ожидаем

2023-12-01 14:25 UTC, MaksimovG commented on js/view-popup.js
> +export const openViewPopup = (evt, url, description, likes, comments) =>{
проигнорированный комментарий

2023-12-01 14:25 UTC, MaksimovG commented on js/view-popup.js
> +  const openedPicture = document.querySelector('.big-picture');
bigPicure лучше. использование глагола запутывает других разработчиков

2023-12-02 17:34 UTC, MaksimovG requested changes

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +  }
не допускается  // eslint-disable-next-line no-use-before-define использование правил отлючающих линтер

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +export const openViewPopup = (evt, url, description, likes, comments) =>{
дважды проигнорированный комментарий

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +  document.removeEventListener('click', closeViewPopup);
на документе висит обработчик клика?  Название обработчика не по критерию

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +  document.removeEventListener('click', closeViewPopup);
да и плюс тут используется обычная функция взмен обработчика - ПЕРЕЧИТЫВАЙТЕ КРИТЕРИИ и пересматривайте лекции. Все было дано

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +  document.removeEventListener('keydown', onCloseBtnClick);
keydown событие onCloseBtnClick обработчик. Какая-то нестыковка

2023-12-02 17:34 UTC, MaksimovG commented on js/view-popup.js
> +  bigPicture.querySelector('.big-picture__cancel').addEventListener('click', closeViewPopup);
элемент находится 1 раз вне функции и потом используется в логике

2023-12-03 04:02 UTC, ElizavetaIlina commented on js/view-popup.js
> +  document.removeEventListener('click', closeViewPopup);
Если убрать evt, аргумент comments ломается и становится типом number, почему его нужно убирать?

2023-12-03 14:41 UTC, MaksimovG requested changes

2023-12-03 14:41 UTC, MaksimovG commented on js/view-popup.js
> +  document.removeEventListener('click', closeViewPopup);
проигнорированные комментарии выше. Непонянтый комментарий про evt. Я не вижу его в этой функции. Видимо не в том месте поставили

2023-12-03 14:41 UTC, MaksimovG commented on js/view-popup.js
> +export const openViewPopup = (evt, url, description, likes, comments) =>{
Трижды проигнорированный комменатрий. Ни в одной лекции evt не передавался куда-то дальше обработчика. Откуда вы взяли эту ненужную стратегию - непонятно

2023-12-03 14:41 UTC, MaksimovG commented on js/view-popup.js
> +  closeViewPopupBtn.addEventListener('click', closeViewPopup);
критерии названия обработчиков

2023-12-03 14:41 UTC, MaksimovG commented on js/view-popup.js
> +  document.addEventListener('keydown', onCloseBtnKeydown);
обработчиков вне запускающих или закрываюбщих логику модуля функций быть не должно

2023-12-04 09:45 UTC, MaksimovG approved these changes

2023-12-04 09:45 UTC, MaksimovG commented on js/view-popup.js
> +  const bigPicture = document.querySelector('.big-picture');
ищем один раз вне функции

2023-12-04 09:45 UTC, MaksimovG commented on js/view-popup.js
> +  const commentsContainer = document.querySelector('.social__comments');
скорее всего тоже вне функции искать надо

2023-12-04 09:45 UTC, MaksimovG commented on js/view-popup.js
> +  const commentsContainer = document.querySelector('.social__comments');
логику с комментариями надо вынести в отдельную функцию

2023-12-04 09:45 UTC, merged